"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JacobiMethod = exports.GaussSeidelMethod = exports.GaussianElimination = exports.LinearSystem = void 0;
var linear_system_1 = require("./models/linear-system");
Object.defineProperty(exports, "LinearSystem", { enumerable: true, get: function () { return linear_system_1.LinearSystem; } });
var gaussian_elimination_1 = require("./solvers/gaussian-elimination");
Object.defineProperty(exports, "GaussianElimination", { enumerable: true, get: function () { return gaussian_elimination_1.GaussianElimination; } });
var gauss_seidel_method_1 = require("./solvers/gauss-seidel-method");
Object.defineProperty(exports, "GaussSeidelMethod", { enumerable: true, get: function () { return gauss_seidel_method_1.GaussSeidelMethod; } });
var jacoby_method_1 = require("./solvers/jacoby-method");
Object.defineProperty(exports, "JacobiMethod", { enumerable: true, get: function () { return jacoby_method_1.JacobiMethod; } });
